api/src/main/scala/org/virtuslab/ideprobe/protocol/BuildResult.scala
api/src/main/scala/org/virtuslab/ideprobe/protocol/FileRef.scala
api/src/main/scala/org/virtuslab/ideprobe/protocol/NavigationTarget.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/ClassFixtures.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/IntegrationTestSuite.scala
driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala
driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/CheckConfig.scala
driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Builds.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Navigation.scala
probePlugin/src/main/scala/org/virtuslab/handlers/PSI.scala
probePlugin/src/main/scala/org/virtuslab/handlers/VFS.scala

- Handle multiple "build steps" (one triggered build can result in multiple separate compilation runs).
- Change FileRef to use Path rather than String
- Add `includeNonProjectItems` parameter to NavigationQuery
- Add 2 fixtures to run shared intellij/workspace for whole test suite
- Extend probe configuration lookup logic to support companion objects and TestName.conf (aditionally to TestName/ideprobe.conf)
- Disable failing on freezes by default (needs to be explicitly enabled)
- `CommandResult.out` throws if command failed (similarly to .!! in scala.process._) We often just run a shell command and take the output, in case command fails, we get unexpected or empty output and the problem is hidden. Output can be always read with `outSafe`, yet we don't even need to e.g. log it, as it is …

Couple of small improvements

---

driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala

Java 9 has override for rewind that returns ByteBuffer, if we run probe under java 8, it throws for no such method.

Cast ByteBuffer to Buffer to maintain compatibility with java 8

---

api/src/main/scala/org/virtuslab/ideprobe/ProbeExtensions.scala
api/src/main/scala/org/virtuslab/ideprobe/protocol/Endpoints.scala
driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
probePlugin/src/main/scala/org/virtuslab/BaseProbeHandlerContributor.scala
probePlugin/src/main/scala/org/virtuslab/handlers/JDK.scala

Can be used before importing scala project, since currently it does not work due to a lack of a predefined jdk

Allow preconfiguring the jdk

---

probePlugin/src/main/scala/org/virtuslab/handlers/Navigation.scala

It throws in thrift plugin test as `getName` is accessing psi

Add read action for item.getName

---

api/src/main/scala/org/virtuslab/ideprobe/protocol/Project.scala
driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
probePlugin/src/main/scala/org/virtuslab/ProbePluginExtensions.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Projects.scala

I used plain case class instead of map with custom types. The original solution was not extensible anyway, now there still is one file that needs to be changed. Additionally we can use default generic derivation of config without extra codecs.
Also api is more convenient:
* no need for `contentRoots.getOrElse(MainSources, Set.empty[Path])`
* no need to import ContentRoot
* no need to contentRoots.values.flatten to inspect all content roots at once

Improve usability of content roots api

---

api/src/main/scala/org/virtuslab/ideprobe/protocol/Endpoints.scala
api/src/main/scala/org/virtuslab/ideprobe/protocol/Sdk.scala
driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Modules.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Projects.scala
probePlugin/src/main/scala/org/virtuslab/handlers/RunConfigurations.scala
probePlugin/src/main/scala/org/virtuslab/handlers/Sdks.scala

* Replace Sdk with proper type
* Remove project from `Modules.resolve`, as we care about `Module` (also avoiding unpacking tuple each time), and Module always has `getProject`, which is more reliable than our resolve.
* Another attempt on fixing robot test

Extend Sdk api

---

driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/IntelliJFixture.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/WorkspaceConfig.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/WorkspaceProvider.scala
driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
project/plugins.sbt

Useful if we don't care about multiple tests interacting with the same workspace (e.g. if each test cleanups after itself or doesn't write anything that can affect other tests). Also useful when setting up repo is costly and/or custom, so it can be prepared externally.

Allow reusing existing workspace

---

driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/WorkspaceProvider.scala

This pull request reduces the clutter in the `/tmp` directory by deleting the leftover empty base directories.
Since the base directory is created along with the workspace directory, I believe it is appropriate to delete it along with the workspace too.
This pull request is related to the issue #22.

Delete the empty parent directory after the workspace is deleted

---

api/src/main/scala/org/virtuslab/ideprobe/ProbeExtensions.scala
api/src/main/scala/org/virtuslab/ideprobe/UUIDs.scala
probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/RunConfigurations.scala

The motivation, purpose and implementation is exactly same as in https://github.com/scalacenter/bloop/pull/851.
Before: `/tmp/workspaces/ideprobe-workspacea5aabeda-930c-422e-8c68-ab9bce1bf81a/ws`
After: `/tmp/workspaces/ideprobe-workspace-uAVmccQ9SZ6SVESwNdmDSw==/ws`

Encode UUIDs with Base 64

---

core/api/src/main/scala/org/virtuslab/ideprobe/ConfigFormat.scala
core/api/src/main/scala/org/virtuslab/ideprobe/protocol/ModuleRef.scala
core/api/src/main/scala/org/virtuslab/ideprobe/protocol/ProjectRef.scala
core/api/src/main/scala/org/virtuslab/ideprobe/protocol/TestScope.scala
core/api/src/test/scala/org/virtuslab/ideprobe/TestScopeParsingTest.scala

This PR adds semi-automatic PureConfig readers for TestScope and all it's components

Adding semi-automatic configuration parser for TestScope

---

build.sbt
core/api/src/main/scala/org/virtuslab/ideprobe/protocol/Endpoints.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/IdeProbePaths.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/WaitLogic.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/PathsConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersion.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Plugin.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJFactory.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/wait/DoOnlyOnce.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/PathsConfigTest.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/BaseProbeHandlerContributor.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Actions.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Editors.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Projects.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/TrustedPaths.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/VFS.scala
extensions/bazel/driver/src/main/scala/org/virtuslab/ideprobe/bazel/BazelProbeDriver.scala
extensions/pants/driver/src/main/scala/org/virtuslab/ideprobe/pants/PantsProbeDriver.scala
extensions/robot/driver/src/main/scala/org/virtuslab/ideprobe/robot/RobotProbeDriver.scala

Add default trusted path to IdeProbePaths and set this path as trusted on startup. By default it is "/"
Factor out Editor related code from Actions
Add sendAsync to ProbeDriver
Allow for doWhileWaiting { driver => ... } (get hold of driver)
Improve toString of IntelliJVersion and Plugin as they show on each probe startup
Update IntelliJ and plugin versions
Set back IntelliJVersion.Latest to point to version from build
DoOnlyOnce.isSuccessful added

Handle (un)trusted projects + refactoring

---

build.sbt
ci/tests/2.12.10/test-probe
ci/tests/2.12.10/test-robot
ci/tests/2.12.10/test-scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersion.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/InternalPlugins.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Plugin.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/PluginResolver.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJFactory.scala
core/driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
core/driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeTestPlugin.scala
extensions/bazel/driver/src/main/scala/org/virtuslab/ideprobe/bazel/BazelPluginExtension.scala
extensions/pants/driver/src/main/scala/org/virtuslab/ideprobe/pants/PantsPluginExtension.scala
extensions/scala/driver/src/main/scala/org/virtuslab/ideprobe/scala/ScalaPluginExtension.scala
project/IdeaPluginAdapter.scala
project/IdeaPluginDevelopment.scala

Adding both scala 2.12 and 2.13 plugins to drivers archives and enabling runtime pick based on IntelliJ version

Adding plugin version switcher to probe drivers

---

core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/JsonRpcEndpoint.scala
core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/logging/RequestResponseLogger.scala
core/api/src/test/scala/org/virtuslab/ideprobe/jsonrpc/logging/RequestResponseLoggerTest.scala

A RequestResponseLogger capable of buffering and counting repeated requests and
responses was created and plugged into JsonRpcEndpoint to reduce noise
in the logs.
Fixes #121

Special logger for JsonRpcEndpoint

---

extensions/bazel/driver/src/main/scala/org/virtuslab/ideprobe/bazel/BazelProbeDriver.scala

This file is used by bazel plugin, for example when invoking project sync or running tests. If we want to use the plugin properly, we can't delete that.
Additionally I moved these files into a hidden subdirectory, to be less messy in the workspace.

Keep bazel viewconfig file through lifetime of the project

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Dependency.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/DependencyProvider.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IntelliJProviderTest.scala

Automatically recognise if it is a zip archive or directory.
Closes: #158

Add support for unzipped IntelliJs in resolvers.intellij.repositories config

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/ResourceProvider.scala

When locally stored, unzipped resource (ex. Intellij) was missing it was `NoSuchFileException` was thrown. Now it is handled correctly.

Fallback to other resolvers if file resource is missing

---

benchmarks/src/main/scala/org/virtuslab/ideprobe/benchmark/BenchmarkSuite.scala
benchmarks/src/main/scala/org/virtuslab/ideprobe/benchmark/report/BenchmarkReporter.scala
benchmarks/src/main/scala/org/virtuslab/ideprobe/benchmark/report/CSVBenchmarkReporter.scala
benchmarks/src/main/scala/org/virtuslab/ideprobe/benchmark/report/CompositeBenchmarkReporter.scala
benchmarks/src/main/scala/org/virtuslab/ideprobe/benchmark/report/ConsoleBenchmarkReporter.scala
benchmarks/src/test/scala/org/virtuslab/ideprobe/benchmark/BenchmarkSuiteTest.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/DependencyProvider.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/ResourceProvider.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala

FileDownloader relies directly on uri, completely ignoring createStream parameter. It breaks building plugin from sources and loading plugins from jars, like bundled plugins (ide-probe extensions are broken). Loading plugins from jars is because FileDownloader asserts that URL returns a HTTP connection, while JarConnection is something else.
I also fixed problematic api like fetch returning option while fetchOpt also exists. 
BenchmarkReporter should be parametrized with type rather than `report` method. In original state there was no type information.

Fix installing bundled plugins (file downloader rollback) and awkward apis

---

build.sbt
core/api/src/main/scala/org/virtuslab/ideprobe/ProbeExtensions.scala
core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/JsonRpc.scala
core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/JsonRpcEndpoint.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/Shell.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/TestCase.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Plugin.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/download/FileDownloader.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/RunningIde.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/reporting/AfterTestChecks.scala
core/driver/test-plugin/src/main/scala/org/virtuslab/ideprobe/test/OpenWindowAction.scala
core/driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/BaseProbeHandlerContributor.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Builds.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Editors.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/ExpandMacro.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Inspections.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/IntelliJApi.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Projects.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/RunConfigurations.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/VCS.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/log/IdeaLogInterceptor.scala
extensions/pants/probePlugin/src/main/scala/org/virtuslab/ideprobe/pants/handlers/PythonProject.scala
extensions/scala/driver/src/main/scala/org/virtuslab/ideprobe/scala/ScalaPluginBuilder.scala
extensions/scala/probePlugin/src/main/scala/org/virtuslab/ideprobe/scala/ScalaProbeHandlerContributor.scala
extensions/scala/probePlugin/src/main/scala/org/virtuslab/ideprobe/scala/handlers/SbtSettings.scala
extensions/scala/probePlugin/src/main/scala/org/virtuslab/ideprobe/scala/handlers/ScalaTestRunConfiguration.scala
project/Dependencies.scala

Fix most of the compilation warnings

---

.github/workflows/update-intellij-version.yml
build.sbt
ci/update-intellij/src/main/resources/intellijVersion.properties
ci/update-intellij/src/main/scala/org.virtuslab.ideprobe/BumpIntelliJ.scala
project/Dependencies.scala

Closes #256
Added scheduled job that would run daily (later to be changed to once a week) to search for new intelliJ release and create a PR if a newer release was found.

add automated intellij version bump

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/git/GitHandler.scala

Closes #274
These changes fix logging of `git-clone` related logs - so that there will be only one line logged for 1% of progress. Changes shorten the total log length for `tests (2.12, probe)` and `tests (2.13 probe)` from 24.000+ lines to less than 3.500 lines.

Make git clone logging less verbose

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IdeProbeConfigTest.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/OfficialResolversTest.scala

Closes #287
Additionally - adds a pattern for snapshot versions with `-EAP-CANDIDATE-SNAPSHOT` suffix

Fix resolving IntelliJ Snapshot versions

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/ResourceProvider.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala

Closes #281
Tested locally against `git-machete-intellij-plugin` - all tests pass properly with following config:
```
probe.resolvers {
intellij.repositories = [
"https://download.jetbrains.com/idea/ideaIC-2022.2.2.dmg"
]
}
```
to be done:

Add support for installing IntelliJ from .dmg

---

.github/workflows/update-intellij-version.yml

Fixes pull requests like this one https://github.com/VirtusLab/ide-probe/pull/286 so that:
- commit author will be set as the bot user
- github actions workflows (CI tests) will be started
The `BOT_ACCESS_TOKEN` is added to secrets. It is a personal access token for the virtuslab-bot user

Fix `update intellij version` pull requests

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala

Related to https://github.com/VirtusLab/ide-probe/issues/238 (but does **not** close it).
Fixes IntelliJ cleanup logic for macOs and makes `SingleRunFixtureTest` tests succeed on macOs **if** `.dmg` extension is used as `probe.intellij.version.ext`.

Fix IntelliJ cleanup logic for macOs

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/wait/WaitLogicFactory.scala

IntelliJ now also reports tasks throught ProgessIndicatorEx (compared to ProgressIndicator without ex). Now these are recongised as named background tasks, while they should not be.

Handle ProgressIndicatorEx as not named bg task

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJPaths.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IntelliJProviderTest.scala
extensions/scala/driver/src/main/scala/org/virtuslab/ideprobe/scala/ScalaPluginExtension.scala

https://github.com/VirtusLab/git-machete-intellij-plugin/issues/1820
TL;DR it seems that under IntelliJ 2024.1 EAP 5, the approach with saving the plugins alongside bundled plugins directory no longer works. ideprobe-provided plugins aren't loaded at all, crashing the test on socket connection attempt. The likely cause are the changes applied for [IJPL-633](https://youtrack.jetbrains.com/issue/IJPL-633).

Store plugins (robot, ide-probe, the tested plugin) in a directory separate from where bundled plugins live
