api/src/main/scala/org/virtuslab/ideprobe/Config.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/IntegrationTestSuite.scala
driver/bindings/junit/src/main/scala/org/virtuslab/ideprobe/IntelliJFixture.scala
driver/tests/src/test/scala/org/virtuslab/ideprobe/ProbeDriverTest.scala
probePlugin/src/main/scala/org/virtuslab/Screenshot.scala
probePlugin/src/main/scala/org/virtuslab/handlers/PSI.scala

Support for config fallbacks
Better fixture transforming from custom suites
Allow running specific action after workspace setup

Fallback config support and minor refactorings

---

README.md
docs/custom-resolvers.md
docs/debug.md
docs/display.md
docs/driver.md
docs/workspace.md

This describes how to configure the ide probe. We still need to describe how to actually use the probe to write tests.

Describe the driver purpose and configuration

---

api/src/main/scala/org/virtuslab/ideprobe/ProbeExtensions.scala

Something strange happens while the directory tree is traversed.

More robust way to delete directories

---

driver/sources/src/main/scala/org/virtuslab/ideprobe/ClassFixtures.scala

Wrapping said vars with Options prevents NullPointerExceptions on `teardown()` in situation when variables are not correctly initialised during `setup()`

Wrapping fixtures variables with Options

---

ci/tests/2.13.1/test-scala
ci/tests/Dockerfile
core/api/src/main/scala/org/virtuslab/ideprobe/protocol/Endpoints.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ProbeDriver.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/BaseProbeHandlerContributor.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/Actions.scala
core/probePlugin/src/main/scala/org/virtuslab/ideprobe/handlers/RunConfigurations.scala
project/CI.scala

Apart from this, include input context in action invocation

New endpoints: open file, jump to line.

---

extensions/bazel/driver/src/main/scala/org/virtuslab/ideprobe/bazel/BazelProbeDriver.scala

Allows for more frequent waiting for benchmarking case,
also allows to extend time limit if needed, in case of builds longer than 15 minutes.

Configurable bazel build waiting

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/DSL.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala

Performing cleanup even after IDE fails to start

---

.github/release-config.yml
.github/workflows/release.yml

This solution is based on how it was done in [akka-serialization-helper](https://github.com/VirtusLab/akka-serialization-helper).
I did not test this solution, because I have no rights to remove the tag and release later ;(

Automatic pushing releases on tags

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/DriverConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/IdeProbeConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
docs/driver.md

I left default parameters as they were 😁

Add new HOCON configuration for resizing screen

---

build.sbt

added -Xfatal-warnings scalac option

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala

Added case class Jar handling

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/Resource.scala

added proper message for ProviderNotFoundException

---

core/api/src/main/scala/org/virtuslab/ideprobe/Config.scala
core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/IdeProbePaths.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/IntelliJFixture.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/CheckConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/DependenciesConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/DriverConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/IdeProbeConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/IntellijConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/PathsConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersion.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/PluginResolver.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IdeProbeConfigTest.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IntelliJProviderTest.scala

Replace default values in code with .conf file

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/JbrResolvers.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/IntelliJProvider.scala

fixed JbrResolvers pattern resolving logic

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/IdeProbePaths.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/PathsConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/PathsConfigTest.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/SingleRunFixtureTest.scala

Make idea logs accessible after shutdown

---

.github/workflows/update-intellij-version.yml

Improve PR body for updating intellij version so that both files where scala intellij plugin version is defined are mentioned.

Improve PR body for updating intellij version

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJVersionResolver.scala

Fix IntelliJVersionResolver.version logic for macOs

---

README.md
core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/DriverConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/DebugMode.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IdeProbeConfigTest.scala
docs/debug.md

Move debug mode configurations to reference.conf

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IdeProbeConfigTest.scala

Make default driver launch command array non-empty

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/IntelliJFixture.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/config/DriverConfig.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/Display.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/ide/intellij/InstalledIntelliJ.scala
core/driver/sources/src/test/resources/example.conf
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IdeProbeConfigTest.scala
core/driver/tests/src/test/resources/CustomCommand/ideprobe.conf

Move headless mode config from `driver.headless` to `driver.display`

---

core/driver/sources/src/main/resources/reference.conf
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/DependencyResolver.scala
core/driver/sources/src/main/scala/org/virtuslab/ideprobe/dependencies/IntelliJResolver.scala
core/driver/sources/src/test/scala/org/virtuslab/ideprobe/dependencies/IntelliJResolverTest.scala

Fix glob resolver stalling on non-existent paths

---

core/driver/sources/src/main/scala/org/virtuslab/ideprobe/wait/WaitLogicFactory.scala

See https://github.com/VirtusLab/git-machete-intellij-plugin/pull/1406

Sift out more types of unnamed background tasks in `WaitLogicFactory#emptyNamedBackgroundTasks`

---

build.sbt
core/api/src/main/scala/org/virtuslab/ideprobe/jsonrpc/logging/GroupingLogger.scala

...as well as SemanticDB to 4.8.14.

Updated Scala versions to 2.12.18 and 2.13.12
